# I modified the github action from @arichornlover 's uYouEnhanced repo, but the original idea is by @ISnackable. Thanks to both of them!
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml

name: Build and Release YouTube Music Premium

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK version to be used during build (don't change it if you don't know what you are doing)"
        default: "16.2"
        required: true
        type: string   
      decrypted_youtube_music_url:
        description: "The direct URL to the decrypted YouTube Music ipa (I recommend using Dropbox, Google Drive is causing errors)"
        default: "https://iosmod.net/IPAs/YouTube_Music_7.25.4.ipa"
        required: true
        type: string
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YouTube Music Premium
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make
              

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: 4bcc52914e0eeca719288522938185decaa8a1cb
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.1
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/thaibm92/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.1
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos
          
      - name: Install Azule
        run: |
          cd ${{ github.workspace }}/main
          git clone https://github.com/Al4ise/Azule 
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule

      - name: Downloading YouTube Music iPA
        run: |
          wget "$YOUTUBE_MUSIC_URL" --no-verbose -O main/YouTubeMusic.ipa

        env:
          YOUTUBE_MUSIC_URL: ${{ inputs.decrypted_youtube_music_url }}    

      - name: Build Tweak for Sideloading
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          make clean package SIDELOADING=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Inject tweak into provided IPA
        run: |
          brew install coreutils
          cd ${{ github.workspace }}/main/packages
          tweakName=$(ls)
          cd ${{ github.workspace }}/main
          ./Azule/azule -i $PWD/YouTubeMusic.ipa -o $PWD/packages/YTMusicUltimate.ipa -f $PWD/packages/$tweakName 

      - name: Prepare YouTube Music iPA
        id: prepare_youtube_music
        run: |
          cd ${{ github.workspace }}/main/packages
          mv YTMusicUltimate.ipa YTMusicUltimate.zip
          unzip YTMusicUltimate.zip
          youtubemusic_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Payload/YouTubeMusic.app/Info.plist")
          echo "==> YouTube Music v$youtubemusic_version Unziped!"
          echo "youtubemusic_version=${youtubemusic_version}" >> $GITHUB_OUTPUT
          cd Payload/YoutubeMusic.app
          rm -rf Watch
          echo "==> Removed Watch folder"
          cd ../..
          zip -r YouTube_Music_Premium_$youtubemusic_version.ipa Payload > /dev/null
          echo "==> YouTube_Music_Premium_$youtubemusic_version.ipa Ziped!"
          rm -rf Payload    

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: YouTubeMusicPremium_${{ steps.prepare_youtube_music.outputs.youtubemusic_version }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
          
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT: ${{ inputs.create_release }}
        with:
          tag_name: v${{ steps.prepare_youtube_music.outputs.youtubemusic_version }}
          name: v${{ steps.prepare_youtube_music.outputs.youtubemusic_version }}
          files: |
            main/packages/*.deb
            main/packages/YouTube_Music_Premium_${{ steps.prepare_youtube_music.outputs.youtubemusic_version }}.ipa
          draft: ${{ env.DRAFT }}
